// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_poCJaNnUyHOHSMf3PkbU0943ZyYtWEI',
    appId: '1:176081394083:web:5a9056ca23fd8c5a73a216',
    messagingSenderId: '176081394083',
    projectId: 'firstproject-65214',
    authDomain: 'firstproject-65214.firebaseapp.com',
    storageBucket: 'firstproject-65214.appspot.com',
    measurementId: 'G-M4TZN2KRGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtibF5EeBzgG_a9ETfW-czWUB_LsDPfYc',
    appId: '1:176081394083:android:cdb0b36a980ba72973a216',
    messagingSenderId: '176081394083',
    projectId: 'firstproject-65214',
    storageBucket: 'firstproject-65214.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW_GfnQAcaOD_8aP4BVG_P-RFnhLoKCbA',
    appId: '1:176081394083:ios:4da2cb653276224d73a216',
    messagingSenderId: '176081394083',
    projectId: 'firstproject-65214',
    storageBucket: 'firstproject-65214.appspot.com',
    iosClientId: '176081394083-olgc3jmdl13b0i51jheof563nshrc22q.apps.googleusercontent.com',
    iosBundleId: 'com.example.kirmizidefter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW_GfnQAcaOD_8aP4BVG_P-RFnhLoKCbA',
    appId: '1:176081394083:ios:4da2cb653276224d73a216',
    messagingSenderId: '176081394083',
    projectId: 'firstproject-65214',
    storageBucket: 'firstproject-65214.appspot.com',
    iosClientId: '176081394083-olgc3jmdl13b0i51jheof563nshrc22q.apps.googleusercontent.com',
    iosBundleId: 'com.example.kirmizidefter',
  );
}
